### PR TITLE
Implement XPluginReceiveMessage callback

### PR DESCRIPTION
**Pull request by telephono**
In my plugin written with the help of `rust-xplm` I needed access to the `XPluginReceiveMessage` callback.
So I tried to implement it myself.

Since I have no expierence interfacing C libraries from Rust I simply tried to adopt the implementation from the code that is already there.
Reading the X-Plane SDK, the `from` parameter probably should be an `i32`, the `message` parameter should be an `u32`. But I'm not sure on how to handle the `param` parameter.

For my project, I only listen for the `XPLM_MSG_LIVERY_LOADED` message. There, the `param` only contains an index to the affected aircraft and a simple cast to `i32` is sufficient. But other messages may contain different data in `param`.
So for now I just tranparently pass the `param` parameter into the plugin's `receive_message` implementation.

### CODE REVIEW

**Comment by samcrow** [comment]
Thanks for contributing. [This documentation](https://developer.x-plane.com/article/developing-plugins/) says that "the message has been, and always will be, a 32-bit signed integer", so I think it would be better to keep the type of message as i32.

**Comment by telephono** [comment]
I chose `u32` because the messages already implemented in `xplm-sys` are `u32`...
image
But this seems to be generated by `bindgen`? It seems this requires further investigation...

**Comment by samcrow** [comment]
The C headers just use `#define`, which leaves it ambiguous. The only clue is that the values don't have the `u` suffix, which suggests signed.

bindgen should be using i32. If there's no easy way to make it do that, re-exporting the values in xplm as i32s would also work.

**Comment by telephono** [comment]
Okay, I changed the message param back to `i32`.
Should I add the messages to the `plugin` module or should I add a `message` module to `plugin`?
```
├── src
│   ├── plugin
│   │   ├── internal.rs
│   │   ├── management.rs
│   │   └── messages.rs
│   ├── plugin.rs
```
I would simply add all messages listed here: [Interplugin Messaging](https://developer.x-plane.com/sdk/XPLMPlugin/#INTERPLUGIN_MESSAGING)

**Comment by samcrow** [comment]
A new "messages" module sounds good.

**Comment by telephono** [comment]
Okay, the `messages` module is already there. But for now it only contains the re-exports of the `XPLM_MSG_*` consts.
In the future, maybe there is even the possibility to create a custom `Message` type which gracefully handles the `c_void` parameter depending on the type of message...

**Comment by samcrow** [comment]
I just published v0.4.2 with these changes.

**Pull request merged**
